Resources:
  smartdocextractbucket90CF6A3D:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - ETag
              - x-amz-meta-custom-header
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-bucket/Resource
  smartdocextractbucketPolicyEC175C33:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: smartdocextractbucket90CF6A3D
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: "false"
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - Fn::GetAtt:
                  - smartdocextractbucket90CF6A3D
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - smartdocextractbucket90CF6A3D
                        - Arn
                    - /*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Principal:
              Service: textract.amazonaws.com
            Resource:
              - Fn::GetAtt:
                  - smartdocextractbucket90CF6A3D
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - smartdocextractbucket90CF6A3D
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-bucket/Policy/Resource
  smartdocextractqueue80660218:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-queue/Resource
  smartdocextractqueuePolicyBCDA074B:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: smartdocextracttopicEEA53D4C
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - smartdocextractqueue80660218
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: smartdocextractqueue80660218
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-queue/Policy/Resource
  smartdocextractqueuetextractexamples3snssqscognitosmartdocextracttopicFFD128FEBB42A55F:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn:
        Ref: smartdocextracttopicEEA53D4C
      Endpoint:
        Fn::GetAtt:
          - smartdocextractqueue80660218
          - Arn
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-queue/textractexamples3snssqscognitosmartdocextracttopicFFD128FE/Resource
  smartdocextracttopicEEA53D4C:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":kms:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - :alias/aws/sns
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-topic/Resource
  smartdocextracttextractrole79875A6E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: textract.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-textract-role/Resource
  smartdocextracttextractroleDefaultPolicyEFEEB181:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sns:Publish
            Effect: Allow
            Resource:
              Ref: smartdocextracttopicEEA53D4C
        Version: "2012-10-17"
      PolicyName: smartdocextracttextractroleDefaultPolicyEFEEB181
      Roles:
        - Ref: smartdocextracttextractrole79875A6E
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-textract-role/DefaultPolicy/Resource
  smartdocextractidA350B90F:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      Schema:
        - Mutable: false
          Name: email
          Required: true
      SmsVerificationMessage: The verification code to your new account is {####}
      UserPoolName: textract-cognito-demo
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-id/Resource
  smartdocextractidsmartdocextractclientidB9ABA9D2:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: smartdocextractidA350B90F
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - profile
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - http://localhost:3000
      ClientName: textract-cognito-demo-client
      SupportedIdentityProviders:
        - COGNITO
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-id/textract-cognito-demo-client-id/Resource
  smartdocextractidsmartdocextractdomainEBB6899F:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: smartdocextract
      UserPoolId:
        Ref: smartdocextractidA350B90F
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-id/textract-cognito-demo-domain/Resource
  smartdocextractidpool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId:
            Ref: smartdocextractidsmartdocextractclientidB9ABA9D2
          ProviderName:
            Fn::GetAtt:
              - smartdocextractidA350B90F
              - ProviderName
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-idpool
  smartdocextractauthenticatedrole685306DF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud:
                  Ref: smartdocextractidpool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
            Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonTextractFullAccess
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-authenticated-role/Resource
  smartdocextractauthenticatedroleDefaultPolicyBF97699E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - mobileanalytics:PutEvents
              - cognito-sync:*
              - cognito-identity:*
            Effect: Allow
            Resource: "*"
          - Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - smartdocextractqueue80660218
                - Arn
          - Action: s3:GetObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - smartdocextractbucket90CF6A3D
                      - Arn
                  - /*
        Version: "2012-10-17"
      PolicyName: smartdocextractauthenticatedroleDefaultPolicyBF97699E
      Roles:
        - Ref: smartdocextractauthenticatedrole685306DF
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/textract-cognito-demo-authenticated-role/DefaultPolicy/Resource
  DefaultValid:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: smartdocextractidpool
      Roles:
        authenticated:
          Fn::GetAtt:
            - smartdocextractauthenticatedrole685306DF
            - Arn
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/DefaultValid
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VQzVLDIBB+lt7ptmk9eFTjxZM11QeIBHWbhE1Z0OkwvLtAGhMv7Pe3HwwF7LY3sF3d1T+8lk278ZKMAn+0tWxFpZickUqUH/rZ2cFZUZJma5y0SVv60WjQIukgUpfnPfgHJ1uVk1c0jgN1KC+zPPIg+MzgX5xyuXAE+ZwXFjTmdcwf3TtLg0O6OiX+8VcaUCY1gyCw7sFX1OUL8pyrp1ZJnxotgX9jZQ5EXTL/8ATKDpW2S+uqTPSR+hr1MjArT01Mor1M7UueXnVv4/d/9VEMIQhNjYITb76LWyh2UKxOjLg2Lq70Cqpx/gIaj5kQyQEAAA==
    Metadata:
      aws:cdk:path: textract-example-s3-sns-sqs-cognito/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  DeployRegion:
    Value:
      Ref: AWS::Region
  DefaultBucketName:
    Value:
      Ref: smartdocextractbucket90CF6A3D
  SNSTopicArn:
    Value:
      Ref: smartdocextracttopicEEA53D4C
  RoleArn:
    Value:
      Fn::GetAtt:
        - smartdocextracttextractrole79875A6E
        - Arn
  QueueUrl:
    Value:
      Ref: smartdocextractqueue80660218
  CognitoId:
    Value:
      Fn::Join:
        - ""
        - - cognito-idp.
          - Ref: AWS::Region
          - .amazonaws.com/
          - Ref: smartdocextractidA350B90F
  CognitoUserPoolId:
    Value:
      Ref: smartdocextractidA350B90F
  CognitoIdentityPoolId:
    Value:
      Ref: smartdocextractidpool
  LoginUrl:
    Value:
      Fn::Join:
        - ""
        - - https://smartdocextract.auth.
          - Ref: AWS::Region
          - .amazoncognito.com/login?client_id=
          - Ref: smartdocextractidsmartdocextractclientidB9ABA9D2
          - "&response_type=token&scope=aws.cognito.signin.user.admin+email+openid+phone+profile&redirect_uri=http://localhost:3000"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
